# Generated by Django 5.2.16 on 2026-07-13 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('base_url', models.URLField()),
                ('username', models.CharField(blank=True, max_length=150)),
                ('encrypted_token', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('owner', models.CharField(max_length=120)),
                ('repository', models.CharField(max_length=120)),
                ('encrypted_token', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'repository'), name='unique_github_repository')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('job_name', models.CharField(max_length=255)),
                ('branch', models.CharField(default='main', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('github_repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.githubrepository')),
                ('jenkins_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.jenkinsserver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failed'), ('ABORTED', 'Aborted'), ('UNSTABLE', 'Unstable'), ('RUNNING', 'Running')], max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='core.projectmapping')),
            ],
            options={
                'ordering': ['-started_at', '-build_number'],
                'constraints': [models.UniqueConstraint(fields=('mapping', 'build_number'), name='unique_mapping_build')],
            },
        ),
    ]
